services:
 db:
   image: mysql:latest
   container_name: tsetyf
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_PASSWORD=password
     - MYSQL_DATABASE=theracity